export default () => [
  {
    id: "top1",
    rank: 1,
    title: "The Shawshank Redemption",
    description:
      "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
    year: 1994,
    rating: "9.2",
    image: "./tssr.jpg",
    genre: ["Drama"],
    director: ["Frank Darabont"],
    writers: ["Stephen King", "Frank Darabont"],
    trailer: "https://www.youtube.com/embed/NmzuHjWmXOc",
  },
  {
    id: "top2",
    rank: 2,
    title: "The Godfather",
    description:
      "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
    year: 1994,
    rating: "9.1",
    image: "./tssr.jpg",
    genre: ["Drama"],
    director: ["Frank Darabont"],
    writers: ["Stephen King", "Frank Darabont"],
    trailer: "https://www.youtube.com/embed/NmzuHjWmXOc",
  },
  {
    id: "top3",
    rank: 3,
    title: "The Shawshank Redemption",
    description:
      "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
    year: 1994,
    rating: "9.2",
    image: "./tssr.jpg",
    genre: ["Drama"],
    director: ["Frank Darabont"],
    writers: ["Stephen King", "Frank Darabont"],
    trailer: "https://www.youtube.com/embed/NmzuHjWmXOc",
  },
  {
    id: "top4",
    rank: 4,
    title: "The Godfather",
    description:
      "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
    year: 1994,
    rating: "9.1",
    image: "./tssr.jpg",
    genre: ["Drama"],
    director: ["Frank Darabont"],
    writers: ["Stephen King", "Frank Darabont"],
    trailer: "https://www.youtube.com/embed/NmzuHjWmXOc",
  },
  {
    id: "top5",
    rank: 5,
    title: "The Shawshank Redemption",
    description:
      "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
    year: 1994,
    rating: "9.2",
    image: "./tssr.jpg",
    genre: ["Drama"],
    director: ["Frank Darabont"],
    writers: ["Stephen King", "Frank Darabont"],
    trailer: "https://www.youtube.com/embed/NmzuHjWmXOc",
  },
  {
    id: "top6",
    rank: 6,
    title: "The Godfather",
    description:
      "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
    year: 1994,
    rating: "9.1",
    image: "./tssr.jpg",
    genre: ["Drama"],
    director: ["Frank Darabont"],
    writers: ["Stephen King", "Frank Darabont"],
    trailer: "https://www.youtube.com/embed/NmzuHjWmXOc",
  },
  {
    id: "top7",
    rank: 7,
    title: "The Shawshank Redemption",
    description:
      "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
    year: 1994,
    rating: "9.2",
    image: "./tssr.jpg",
    genre: ["Drama"],
    director: ["Frank Darabont"],
    writers: ["Stephen King", "Frank Darabont"],
    trailer: "https://www.youtube.com/embed/NmzuHjWmXOc",
  },
  {
    id: "top8",
    rank: 8,
    title: "The Godfather",
    description:
      "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
    year: 1994,
    rating: "9.1",
    image: "./tssr.jpg",
    genre: ["Drama"],
    director: ["Frank Darabont"],
    writers: ["Stephen King", "Frank Darabont"],
    trailer: "https://www.youtube.com/embed/NmzuHjWmXOc",
  },
  {
    id: "top9",
    rank: 9,
    title: "The Godfather",
    description:
      "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
    year: 1994,
    rating: "9.1",
    image: "./tssr.jpg",
    director: ["Frank Darabont"],
    genre: ["Drama"],
    writers: ["Stephen King", "Frank Darabont"],
    trailer: "https://www.youtube.com/embed/NmzuHjWmXOc",
  },
  {
    id: "top10",
    rank: 10,
    title: "The Godfather",
    description:
      "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
    year: 1994,
    rating: "9.1",
    image: "./tssr.jpg",
    genre: ["Drama"],
    director: ["Frank Darabont"],
    writers: ["Stephen King", "Frank Darabont"],
    trailer: "https://www.youtube.com/embed/NmzuHjWmXOc",
  },
  {
    id: "top11",
    rank: 11,
    title: "The Godfather",
    description:
      "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
    year: 1994,
    rating: "9.1",
    image: "./tssr.jpg",
    genre: ["Drama"],
    director: ["Frank Darabont"],
    writers: ["Stephen King", "Frank Darabont"],
    trailer: "https://www.youtube.com/embed/NmzuHjWmXOc",
  },
  {
    id: "top12",
    rank: 12,
    title: "The Godfather",
    description:
      "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
    year: 1994,
    rating: "9.1",
    image: "./tssr.jpg",
    genre: ["Drama"],
    director: ["Frank Darabont"],
    writers: ["Stephen King", "Frank Darabont"],
    trailer: "https://www.youtube.com/embed/NmzuHjWmXOc",
  },
  {
    id: "top13",
    rank: 13,
    title: "The Godfather",
    description:
      "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
    year: 1994,
    rating: "9.1",
    image: "./tssr.jpg",
    genre: ["Drama"],
    director: ["Frank Darabont"],
    writers: ["Stephen King", "Frank Darabont"],
    trailer: "https://www.youtube.com/embed/NmzuHjWmXOc",
  },
];
